### ISSUE TITLE
Blank window when opening the clipboard menu

### ISSUE THREAD

**Issue by dudul** [nakkag/CLCL#2]
Hi,
I'm using this app for the last years and love it.
About a week ago I started to  get a blank window when opening the clipboard menu.
When I close this window the app is closing too.

CLCL Ver 2.1.1
![CIhznUZKYr](https://user-images.githubusercontent.com/4558838/145717829-b0770694-7bd7-4ccf-a0de-882cfc59f67e.png)

**Comment by nakkag** [comment]
The main screen, which is originally hidden, is displayed. Check if the main screen is forcibly displayed by another application.
