### ISSUE TITLE
Sometimes I switch off CLCL by mistake - new ICON could help

### ISSUE THREAD

**Issue by realrelook** [nakkag/CLCL#3]
Hello, great piece of software.
But sometimes I switch off CLCL by mis-typing and the icon in the windows taskbar is changing color only slightly. I wish you could change the *off* or *offline* icon to a more colorfull version.
Like the one attached.
![ico00006_sk](https://user-images.githubusercontent.com/98465420/151166802-f0aa5489-9a05-42ed-b799-786fcdd6f3f0.png)

That would be great. And keep the rest of code like it is....... perfect things don't need a change.

Or can I exchange the icon by myself.??

Thank you in advance.!!!

**Comment by nakkag** [comment]
Change icon.

![image](https://user-images.githubusercontent.com/93958337/173484376-bd86eaef-760d-44fd-b44a-bf8cd9ad9370.png)

**Comment by realrelook** [comment]
申し訳ありませんが、「記号3からクリップボードを変更する」というコメントが理解できません。シンボルマークがどこにもないんです。

Sorry, but I don't understand your comment 'Change clipboard from symbol #3'. I can't find the symbols anywhere.

**Comment by nakkag** [comment]
Not yet released.
Please wait for release.

**Comment by realrelook** [comment]
Good day. Do you already have a new version in planning? When will it be released? Have a nice vacation season.
ごきげんよう。すでに新バージョンの企画があるのでしょうか？いつ公開されるのですか？素敵なホリデーシーズンをお過ごしください。
Guten Tag. Haben Sie schon eine neue Version in Planung.? Wann wir die veröffentlicht werden.? Schon mal schöne Ferienzeit wünsche ich Ihnen.

**Comment by nakkag** [comment]
2.1.3 has been released.
